"""Published default physical-activity form v2 — structured fields, same consent keys."""

from __future__ import annotations

from typing import Any


def _opts(*pairs: tuple[str, str]) -> list[dict[str, str]]:
    return [{"value": a, "label": b} for a, b in pairs]


def _q(
    qid: str,
    *,
    label: str,
    qtype: str = "text",
    required: bool = False,
    sensitive: bool = False,
    attention: bool = False,
    options: list[dict[str, str]] | None = None,
    help_text: str | None = None,
    placeholder: str | None = None,
    section: str,
    visible_if: dict[str, Any] | None = None,
    optional: bool = False,
) -> dict[str, Any]:
    item: dict[str, Any] = {
        "id": qid,
        "label": label,
        "type": qtype,
        "required": required,
        "sensitive": sensitive,
        "attention": attention,
        "section": section,
        "optional": optional or not required,
    }
    if options is not None:
        item["options"] = options
    if help_text is not None:
        item["help_text"] = help_text
    if placeholder is not None:
        item["placeholder"] = placeholder
    if visible_if is not None:
        item["visible_if"] = visible_if
    return item


YES_NO = _opts(("nao", "Não"), ("sim", "Sim"))
YES_NO_UNK = _opts(
    ("nao", "Não"),
    ("sim", "Sim"),
    ("nao_sei", "Não sei"),
    ("prefiro_nao_informar", "Prefiro não informar"),
)
TRIAGE = _opts(
    ("nao", "Não"),
    ("sim", "Sim"),
    ("nao_sei", "Não sei"),
    ("prefiro_nao_informar", "Prefiro não informar"),
)


def build_schema_v2() -> dict[str, Any]:
    def vif(qid: str, *values: str) -> dict[str, Any]:
        return {"question_id": qid, "in": list(values)}

    sections = [
        {
            "id": "A",
            "title": "Objetivos",
            "questions": [
                _q(
                    "a_primary_goal",
                    label="Qual é o seu objetivo principal?",
                    required=True,
                    section="A",
                    qtype="long_text",
                    help_text="Resuma em poucas palavras o que você gostaria de alcançar.",
                    placeholder="Ex.: melhorar o condicionamento e manter uma rotina constante.",
                ),
                _q(
                    "a_secondary_goals",
                    label="Há outros objetivos?",
                    section="A",
                    qtype="long_text",
                    optional=True,
                    placeholder="Ex.: ganhar mobilidade ou reduzir o cansaço no dia a dia.",
                ),
                _q(
                    "a_timeline",
                    label="Há algum prazo em mente?",
                    section="A",
                    qtype="single_choice",
                    optional=True,
                    options=_opts(
                        ("sem_prazo", "Sem prazo definido"),
                        ("1_3_meses", "1 a 3 meses"),
                        ("4_6_meses", "4 a 6 meses"),
                        ("mais_6_meses", "Mais de 6 meses"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "a_prior_experience",
                    label="Você já treinou ou praticou com acompanhamento?",
                    section="A",
                    qtype="single_choice",
                    options=YES_NO_UNK,
                ),
            ],
        },
        {
            "id": "B",
            "title": "Histórico de atividade física",
            "questions": [
                _q(
                    "b_currently_active",
                    label="Você pratica atividade física atualmente?",
                    qtype="single_choice",
                    options=YES_NO,
                    section="B",
                ),
                _q(
                    "b_weekly_frequency",
                    label="Com que frequência você pratica (ou pretende praticar)?",
                    qtype="single_choice",
                    section="B",
                    options=_opts(
                        ("1", "1 vez por semana"),
                        ("2", "2 vezes"),
                        ("3", "3 vezes"),
                        ("4", "4 vezes"),
                        ("5_mais", "5 ou mais"),
                        ("ainda_nao_sei", "Ainda não sei"),
                        ("outra", "Outra frequência"),
                    ),
                ),
                _q(
                    "b_weekly_frequency_other",
                    label="Qual frequência?",
                    qtype="text",
                    section="B",
                    optional=True,
                    visible_if=vif("b_weekly_frequency", "outra"),
                    placeholder="Ex.: 6 vezes ou a cada 15 dias.",
                ),
                _q(
                    "b_session_duration",
                    label="Qual duração média das sessões?",
                    qtype="single_choice",
                    section="B",
                    options=_opts(
                        ("ate_30", "Até 30 minutos"),
                        ("45", "45 minutos"),
                        ("60", "1 hora"),
                        ("90", "1h30"),
                        ("mais_90", "Mais de 1h30"),
                        ("varia", "Varia"),
                        ("ainda_nao_sei", "Ainda não sei"),
                    ),
                ),
                _q(
                    "b_modalities",
                    label="Quais modalidades você pratica ou tem interesse?",
                    qtype="multi",
                    section="B",
                    help_text="Pode escolher mais de uma.",
                    options=_opts(
                        ("musculacao", "Musculação"),
                        ("corrida", "Corrida"),
                        ("caminhada", "Caminhada"),
                        ("funcional", "Funcional"),
                        ("natacao", "Natação"),
                        ("ciclismo", "Ciclismo"),
                        ("danca", "Dança"),
                        ("luta", "Luta"),
                        ("pilates", "Pilates"),
                        ("futebol", "Futebol"),
                        ("outra", "Outra"),
                    ),
                ),
                _q(
                    "b_modalities_other",
                    label="Qual modalidade?",
                    qtype="text",
                    section="B",
                    optional=True,
                    visible_if=vif("b_modalities", "outra"),
                    placeholder="Ex.: yoga ou tênis.",
                ),
                _q(
                    "b_time_inactive",
                    label="Há quanto tempo você não pratica?",
                    qtype="single_choice",
                    section="B",
                    help_text="Responda apenas se já praticou anteriormente.",
                    optional=True,
                    options=_opts(
                        ("pratico_atualmente", "Pratico atualmente"),
                        ("menos_1_mes", "Menos de 1 mês"),
                        ("1_3_meses", "1 a 3 meses"),
                        ("4_6_meses", "4 a 6 meses"),
                        ("7_12_meses", "7 a 12 meses"),
                        ("mais_1_ano", "Mais de 1 ano"),
                        ("nunca", "Nunca pratiquei"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "b_past_difficulties",
                    label="Quais dificuldades você já teve?",
                    qtype="long_text",
                    section="B",
                    optional=True,
                    help_text="Pode ser sobre execução, organização, motivação ou acompanhamento.",
                    placeholder="Ex.: não sabia quais exercícios fazer ou em que ordem.",
                ),
                _q(
                    "b_preferences",
                    label="Existe algo que você gostaria de priorizar?",
                    qtype="multi",
                    section="B",
                    help_text="Pode ser uma atividade, objetivo ou parte do corpo, quando aplicável.",
                    optional=True,
                    options=_opts(
                        ("forca", "Força"),
                        ("resistencia", "Resistência"),
                        ("mobilidade", "Mobilidade"),
                        ("condicionamento", "Condicionamento"),
                        ("emagrecimento", "Emagrecimento"),
                        ("massa", "Ganho de massa"),
                        ("bem_estar", "Bem-estar"),
                        ("outra", "Outra prioridade"),
                        ("ainda_nao_sei", "Ainda não sei"),
                    ),
                ),
                _q(
                    "b_preferences_other",
                    label="Quer acrescentar algo?",
                    qtype="text",
                    section="B",
                    optional=True,
                    placeholder="Ex.: melhorar resistência, fortalecer pernas ou praticar corrida.",
                ),
                _q(
                    "b_dislikes",
                    label="Existe alguma atividade que você não gosta?",
                    qtype="single_choice",
                    section="B",
                    help_text="Isso ajuda o profissional a considerar suas preferências.",
                    options=_opts(("nao", "Não"), ("sim", "Sim"), ("nao_sei", "Não sei")),
                ),
                _q(
                    "b_dislikes_detail",
                    label="Quais atividades você prefere evitar?",
                    qtype="multi",
                    section="B",
                    optional=True,
                    visible_if=vif("b_dislikes", "sim"),
                    options=_opts(
                        ("corrida", "Corrida"),
                        ("repetitivos", "Exercícios repetitivos"),
                        ("grupo", "Atividades em grupo"),
                        ("alto_impacto", "Exercícios de alto impacto"),
                        ("outra", "Outra"),
                    ),
                ),
            ],
        },
        {
            "id": "C",
            "title": "Rotina e disponibilidade",
            "questions": [
                _q(
                    "c_available_days",
                    label="Quais dias costumam funcionar melhor?",
                    qtype="multi",
                    section="C",
                    options=_opts(
                        ("seg", "Segunda"),
                        ("ter", "Terça"),
                        ("qua", "Quarta"),
                        ("qui", "Quinta"),
                        ("sex", "Sexta"),
                        ("sab", "Sábado"),
                        ("dom", "Domingo"),
                        ("ainda_nao_sei", "Ainda não sei"),
                    ),
                ),
                _q(
                    "c_available_periods",
                    label="Quais períodos funcionam melhor?",
                    qtype="multi",
                    section="C",
                    options=_opts(
                        ("manha", "Manhã"),
                        ("tarde", "Tarde"),
                        ("noite", "Noite"),
                        ("flexivel", "Horário flexível"),
                    ),
                ),
                _q(
                    "c_specific_time",
                    label="Deseja informar algum horário específico?",
                    qtype="single_choice",
                    section="C",
                    options=YES_NO,
                ),
                _q(
                    "c_available_times",
                    label="Qual horário?",
                    qtype="text",
                    section="C",
                    optional=True,
                    visible_if=vif("c_specific_time", "sim"),
                    placeholder="Ex.: depois das 18h.",
                ),
                _q(
                    "c_location",
                    label="Onde você prefere realizar as atividades?",
                    qtype="single_choice",
                    section="C",
                    options=_opts(
                        ("academia", "Academia"),
                        ("casa", "Em casa"),
                        ("ar_livre", "Ao ar livre"),
                        ("estudio", "Estúdio"),
                        ("online", "Online"),
                        ("ainda_nao_defini", "Ainda não defini"),
                        ("outro", "Outro"),
                    ),
                ),
                _q(
                    "c_location_other",
                    label="Qual local?",
                    qtype="text",
                    section="C",
                    optional=True,
                    visible_if=vif("c_location", "outro"),
                ),
                _q(
                    "c_routine_type",
                    label="Como é a sua rotina na maior parte do dia?",
                    qtype="single_choice",
                    section="C",
                    options=_opts(
                        ("sentada", "Predominantemente sentada"),
                        ("em_pe", "Predominantemente em pé"),
                        ("ativa", "Bastante ativa"),
                        ("varia", "Varia ao longo do dia"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "c_time_limits",
                    label="Existe alguma limitação de horário importante?",
                    qtype="single_choice",
                    section="C",
                    options=YES_NO,
                ),
                _q(
                    "c_time_limits_detail",
                    label="Qual limitação?",
                    qtype="text",
                    section="C",
                    optional=True,
                    visible_if=vif("c_time_limits", "sim"),
                    help_text="Ex.: preciso encerrar até 8h ou só consigo após 18h.",
                    placeholder="Ex.: preciso encerrar até 8h.",
                ),
            ],
        },
        {
            "id": "D",
            "title": "Histórico de saúde declarado",
            "questions": [
                _q(
                    "d_cardiovascular",
                    label="Você possui alguma condição cardiovascular declarada?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_cardiovascular_detail",
                    label="Quer complementar?",
                    qtype="text",
                    sensitive=True,
                    section="D",
                    optional=True,
                    visible_if=vif("d_cardiovascular", "sim"),
                    placeholder="Informe apenas o que considerar importante.",
                ),
                _q(
                    "d_blood_pressure",
                    label="Você tem alteração de pressão arterial?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_respiratory",
                    label="Você possui alguma condição respiratória?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_metabolic",
                    label="Você tem diabetes ou outra alteração metabólica?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_fainting",
                    label="Você já teve desmaios ou tonturas relevantes?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_chest_pain",
                    label="Você sente dor no peito?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_unusual_breathlessness",
                    label="Você sente falta de ar incomum?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_neurological",
                    label="Você possui alguma condição neurológica declarada?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_musculoskeletal",
                    label="Você possui alguma condição musculoesquelética?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="D",
                ),
                _q(
                    "d_other_conditions",
                    label="Há outras condições relevantes?",
                    qtype="long_text",
                    sensitive=True,
                    section="D",
                    optional=True,
                ),
                _q(
                    "d_medical_followup",
                    label="Você está em acompanhamento médico atualmente?",
                    qtype="single_choice",
                    options=YES_NO_UNK,
                    sensitive=True,
                    section="D",
                ),
            ],
        },
        {
            "id": "E",
            "title": "Lesões, cirurgias, dores e limitações",
            "questions": [
                _q(
                    "e_current_injury",
                    label="Você possui alguma lesão atualmente?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="E",
                ),
                _q(
                    "e_current_injury_detail",
                    label="Qual região ou descrição curta?",
                    qtype="text",
                    sensitive=True,
                    section="E",
                    optional=True,
                    visible_if=vif("e_current_injury", "sim"),
                    help_text="Informe apenas o que considerar importante para o acompanhamento.",
                ),
                _q(
                    "e_prior_injury",
                    label="Você já teve alguma lesão relevante?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    section="E",
                ),
                _q(
                    "e_prior_injury_detail",
                    label="Qual lesão ou região foi afetada?",
                    qtype="text",
                    sensitive=True,
                    section="E",
                    optional=True,
                    visible_if=vif("e_prior_injury", "sim"),
                    help_text="Informe apenas o que considerar importante para o acompanhamento.",
                    placeholder="Ex.: lesão no joelho direito há dois anos.",
                ),
                _q(
                    "e_limited_movements",
                    label="Isso ainda limita alguma atividade?",
                    qtype="single_choice",
                    options=_opts(
                        ("nao", "Não"),
                        ("sim", "Sim"),
                        ("as_vezes", "Às vezes"),
                        ("nao_sei", "Não sei"),
                    ),
                    sensitive=True,
                    section="E",
                    visible_if=vif("e_prior_injury", "sim"),
                ),
                _q(
                    "e_surgery",
                    label="Você já realizou alguma cirurgia relevante?",
                    qtype="single_choice",
                    options=_opts(
                        ("nao", "Não"),
                        ("sim", "Sim"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                    sensitive=True,
                    section="E",
                ),
                _q(
                    "e_surgery_detail",
                    label="Qual cirurgia e quando ocorreu?",
                    qtype="text",
                    sensitive=True,
                    section="E",
                    optional=True,
                    visible_if=vif("e_surgery", "sim"),
                    placeholder="Ex.: cirurgia no joelho em 2024.",
                ),
                _q(
                    "e_current_pain",
                    label="Você sente alguma dor atualmente?",
                    qtype="single_choice",
                    options=_opts(
                        ("nao", "Não"),
                        ("sim", "Sim"),
                        ("as_vezes", "Às vezes"),
                        ("nao_sei", "Não sei"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                    sensitive=True,
                    attention=True,
                    section="E",
                ),
                _q(
                    "e_pain_region",
                    label="Em qual região?",
                    qtype="text",
                    sensitive=True,
                    section="E",
                    optional=True,
                    visible_if=vif("e_current_pain", "sim", "as_vezes"),
                ),
                _q(
                    "e_pain_intensity",
                    label="Intensidade declarada (0 a 10)",
                    qtype="scale",
                    sensitive=True,
                    section="E",
                    optional=True,
                    visible_if=vif("e_current_pain", "sim", "as_vezes"),
                    options=[{"value": str(i), "label": str(i)} for i in range(11)],
                ),
            ],
        },
        {
            "id": "F",
            "title": "Medicamentos declarados",
            "questions": [
                _q(
                    "f_meds_affect_exercise",
                    label="Você utiliza algum medicamento que considere importante informar?",
                    qtype="single_choice",
                    options=_opts(
                        ("nao", "Não"),
                        ("sim", "Sim"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                    sensitive=True,
                    attention=True,
                    section="F",
                ),
                _q(
                    "f_meds_notes",
                    label="Observações sobre medicamentos",
                    qtype="text",
                    sensitive=True,
                    section="F",
                    optional=True,
                    visible_if=vif("f_meds_affect_exercise", "sim"),
                ),
            ],
        },
        {
            "id": "G",
            "title": "Triagem de prontidão para atividade",
            "questions": [
                _q(
                    "g_chest_pain_exertion",
                    label="Sente dor no peito ao se esforçar?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="G",
                    help_text="Respostas de atenção serão analisadas pelo profissional.",
                ),
                _q(
                    "g_dizziness_exertion",
                    label="Sente tontura ou desmaio ao se esforçar?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="G",
                ),
                _q(
                    "g_bone_joint_problem",
                    label="Tem problema ósseo ou articular que piore com exercício?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="G",
                ),
                _q(
                    "g_doctor_advised_limit",
                    label="Algum profissional de saúde aconselhou limitar atividade física?",
                    qtype="single_choice",
                    options=TRIAGE,
                    sensitive=True,
                    attention=True,
                    section="G",
                ),
            ],
        },
        {
            "id": "H",
            "title": "Hábitos e recuperação",
            "questions": [
                _q(
                    "h_sleep",
                    label="Como você avalia o seu sono?",
                    qtype="single_choice",
                    section="H",
                    optional=True,
                    options=_opts(
                        ("bom", "Bom"),
                        ("regular", "Regular"),
                        ("ruim", "Ruim"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "h_stress",
                    label="Como você percebe o estresse no dia a dia?",
                    qtype="single_choice",
                    section="H",
                    optional=True,
                    options=_opts(
                        ("baixo", "Baixo"),
                        ("moderado", "Moderado"),
                        ("alto", "Alto"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "h_smoking",
                    label="Tabagismo",
                    qtype="single_choice",
                    section="H",
                    options=_opts(
                        ("nao", "Não"),
                        ("sim", "Sim"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "h_alcohol",
                    label="Consumo de álcool",
                    qtype="single_choice",
                    section="H",
                    options=_opts(
                        ("nao", "Não"),
                        ("sim", "Sim"),
                        ("prefiro_nao_informar", "Prefiro não informar"),
                    ),
                ),
                _q(
                    "h_free_notes",
                    label="Quer acrescentar alguma observação?",
                    qtype="long_text",
                    section="H",
                    optional=True,
                ),
            ],
        },
        {
            "id": "I",
            "title": "Preferências de acompanhamento",
            "questions": [
                _q(
                    "i_desired_frequency",
                    label="Com que frequência você deseja realizar os atendimentos?",
                    qtype="single_choice",
                    section="I",
                    options=_opts(
                        ("1", "1 vez por semana"),
                        ("2", "2 vezes por semana"),
                        ("3", "3 vezes por semana"),
                        ("4", "4 vezes por semana"),
                        ("5_mais", "5 ou mais"),
                        ("ainda_nao_sei", "Ainda não sei"),
                        ("outra", "Outra"),
                    ),
                ),
                _q(
                    "i_contact_preference",
                    label="Como prefere ser contatado?",
                    qtype="multi",
                    section="I",
                    options=_opts(
                        ("whatsapp", "WhatsApp"),
                        ("ligacao", "Ligação"),
                        ("email", "E-mail"),
                        ("tanto_faz", "Tanto faz"),
                    ),
                ),
                _q(
                    "i_reminders",
                    label="Deseja receber lembretes?",
                    qtype="single_choice",
                    section="I",
                    help_text="Você poderá alterar essa preferência depois.",
                    options=YES_NO,
                ),
                _q(
                    "i_feedback_requests",
                    label="Pode receber solicitações de acompanhamento periódico?",
                    qtype="single_choice",
                    section="I",
                    help_text="O profissional poderá solicitar acompanhamentos periódicos.",
                    options=YES_NO,
                ),
                _q(
                    "i_best_contact_period",
                    label="Qual o melhor período para contato?",
                    qtype="single_choice",
                    section="I",
                    options=_opts(
                        ("manha", "Manhã"),
                        ("tarde", "Tarde"),
                        ("noite", "Noite"),
                        ("qualquer", "Qualquer período"),
                    ),
                ),
            ],
        },
        {
            "id": "J",
            "title": "Declarações e consentimentos",
            "questions": [],
            "consents": [
                {
                    "key": "purpose_science",
                    "required": True,
                    "label": "Declaro ciência da finalidade deste cadastro e anamnese.",
                    "text_version": "v1",
                    "group": "required",
                },
                {
                    "key": "sensitive_health",
                    "required": True,
                    "label": "Autorizo o tratamento dos dados de saúde que declarei, apenas para este profissional.",
                    "text_version": "v1",
                    "group": "required",
                },
                {
                    "key": "self_declared",
                    "required": True,
                    "label": "Declaro que as respostas foram fornecidas por mim.",
                    "text_version": "v1",
                    "group": "required",
                },
                {
                    "key": "not_medical",
                    "required": True,
                    "label": "Estou ciente de que este formulário não substitui avaliação médica.",
                    "text_version": "v1",
                    "group": "required",
                },
                {
                    "key": "privacy_policy",
                    "required": True,
                    "label": "Li e aceito a política de privacidade.",
                    "text_version": "v1",
                    "group": "required",
                },
                {
                    "key": "whatsapp_optional",
                    "required": False,
                    "label": "Autorizo contato por WhatsApp (opcional).",
                    "text_version": "v1",
                    "group": "optional",
                },
            ],
        },
    ]
    return {
        "code": "croniu_default_physical_activity",
        "name": "Anamnese de atividade física — padrão Croniu",
        "version": 2,
        "sections": sections,
        "attention_client_message": (
            "Suas respostas indicam que alguns pontos precisam ser analisados "
            "pelo profissional antes do início das atividades."
        ),
    }
